const axios = require('axios');

class AIService {
  constructor() {
    this.provider = process.env.AI_PROVIDER || 'mock';
  }

  async generateResponse(prompt, context = []) {
    if (this.provider === 'mock') {
      return this.mockResponse(prompt);
    } else if (this.provider === 'openai') {
      return this.openaiResponse(prompt, context);
    } else if (this.provider === 'gemini') {
      return this.geminiResponse(prompt, context);
    }
    return "AI Provider not configured correctly.";
  }

  async mockResponse(prompt) {
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    const lowerPrompt = prompt.toLowerCase();
    if (lowerPrompt.includes('theft') || lowerPrompt.includes('steal')) {
      return "Under IPC Section 378, Theft is defined as moving any moveable property out of the possession of any person without that person's consent. The punishment (Section 379) can extend to 3 years imprisonment.";
    }
    if (lowerPrompt.includes('murder') || lowerPrompt.includes('kill')) {
      return "Murder is defined under Section 300 of the IPC. The punishment for murder is defined in Section 302, which includes death or imprisonment for life, and shall also be liable to fine.";
    }
    if (lowerPrompt.includes('cheating')) {
      return "Cheating is defined under Section 415 of the IPC. It involves deceiving any person effectively to deliver any property. Punishment is defined under Section 417.";
    }
    
    return `This is a simulated AI response for: "${prompt}". To get real responses, configure OPENAI_API_KEY or GEMINI_API_KEY in .env and set AI_PROVIDER.`;
  }

  async openaiResponse(prompt, context) {
    try {
      // Basic implementation for OpenAI
      // In a real app, use the official library
      const messages = context.map(msg => ({ role: msg.role, content: msg.content }));
      messages.push({ role: 'user', content: prompt });
      
      const response = await axios.post('https://api.openai.com/v1/chat/completions', {
        model: "gpt-3.5-turbo",
        messages: messages
      }, {
        headers: { 'Authorization': `Bearer ${process.env.OPENAI_API_KEY}` }
      });
      return response.data.choices[0].message.content;
    } catch (error) {
      console.error("OpenAI Error:", error.message);
      if (error.response) {
        console.error("OpenAI Error Details:", JSON.stringify(error.response.data));
      }
      return "Error communicating with AI service.";
    }
  }
  
  // Gemini Integration
  async geminiResponse(prompt, context) {
    try {
      const apiKey = process.env.GEMINI_API_KEY ? process.env.GEMINI_API_KEY.trim() : '';
      if (!apiKey) return "Gemini API Key is missing.";

      // Use gemini-flash-latest for better stability
      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${apiKey}`;
      
      // Convert context to Gemini format
      // Add a system instruction as the first message
      const contents = [
        {
          role: 'user',
          parts: [{ text: "You are an expert Indian Legal AI Assistant. Your goal is to provide accurate legal advice based on Indian Laws (IPC, CrPC, IT Act). Always include relevant sections, filing procedures, and strategic advice." }]
        },
        {
          role: 'model',
          parts: [{ text: "Understood. I will act as an expert Indian Legal AI Assistant and provide comprehensive advice including sections, case laws, procedures, and strategies." }]
        }
      ];

      // Append conversation history
      context.forEach(msg => {
        contents.push({
          role: msg.role === 'assistant' ? 'model' : 'user',
          parts: [{ text: msg.content }]
        });
      });
      
      // Append current prompt (which might contain RAG context)
      contents.push({
        role: 'user',
        parts: [{ text: prompt }]
      });

      const response = await axios.post(url, {
        contents: contents
      });
      
      if (response.data && response.data.candidates && response.data.candidates.length > 0) {
        return response.data.candidates[0].content.parts[0].text;
      }
      
      return "No response generated by Gemini.";
    } catch (error) {
       console.error("Gemini Error:", error.message);
       if (error.response) {
         console.error("Gemini Error Details:", JSON.stringify(error.response.data));
       }
       // Fallback to mock on error
       console.log("Falling back to Mock response due to Gemini error.");
       return this.mockResponse(prompt);
    }
  }
}

module.exports = new AIService();
